apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgen
data:
  FRONTEND_ADDR: ""
  #USERS: "50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
      project: hipstershop
      tier: web
  template:
    metadata:
      labels:
        app: loadgen
        project: hipstershop
        tier: web
    spec:
      containers:
        - name: loadgen
          image: srikanthhg/loadgen:v1
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: loadgen
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loadgen
spec:
  type: LoadBalancer
  selector:
    app: loadgen
    project: hipstershop
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 8080