apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: emailservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: email
          image: srikanthhg/emailservice:v1
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: emailservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi