apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: adservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: adservice
          image: srikanthhg/adservice:v1
          ports:
          - containerPort: 9555
          envFrom:
          - configMapRef:
              name: adservice
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi