apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      project: hipstershop
      tier: web
  template:
    metadata:
      labels:
        app: frontend
        project: hipstershop
        tier: web
    spec:
      containers:
        - name: frontend
          image: srikanthhg/frontend:v1
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: frontend
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi