apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendationservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: recommendationservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: recommendation
          image: srikanthhg/recommendationservice:v1
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: recommendationservice
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi