apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: productcatalogservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: productcatalog
          image: srikanthhg/productcatalogservice:v1
          ports:
          - containerPort: 3550
          envFrom:
          - configMapRef:
              name: productcatalogservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi