apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shippingservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: shippingservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: shipping
          image: srikanthhg/shippingservice:v1
          ports:
          - containerPort: 50051
          envFrom:
          - configMapRef:
              name: shippingservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi