apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currencyservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: currencyservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: currency
          image: srikanthhg/currencyservice:v1
          ports:
          - containerPort: 7000
          envFrom:
          - configMapRef:
              name: currencyservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi