apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: cartservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: cart
          image: srikanthhg/cartservice:v1
          ports:
          - containerPort: 7070
          envFrom:
          - configMapRef:
              name: cartservice
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi